spring:
  application:
    name: item_service
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem://localhost/~/test
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.jdbc: debug