spring:
  application:
    name: springtx

logging:
  level:
    org.springframework.transaction.interceptor: trace
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.hibernate.resource.transaction: debug
    org.hibernate.SQL: debug